apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-helm
  template:
    metadata:
      labels:
        app: hello-helm
    spec:
      containers:
        - name: hello-helm
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
