apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    app: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: nginxdemos/hello
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "20Mi"
          limits:
            cpu: "200m"
            memory: "20Mi"
        envFrom:
        - configMapRef:
            name: hello-app-config
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: hello-app-secret
              key: API_KEY
